name: 'Django Migrations Action'
description: 'Handles Django database migrations'
inputs:
  DJANGO_DB_HOST:
    description: 'Database host'
    required: true
  DJANGO_DB_PORT:
    description: 'Database port'
    required: true
  DJANGO_DB_NAME:
    description: 'Database name'
    required: true
  DJANGO_DB_USER:
    description: 'Database user'
    required: true
  DJANGO_DB_PASSWORD:
    description: 'Database password'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Python 3.8
      run: |
        sudo apt-get update
        sudo apt-get install python3.8 python3-pip
        python3.8 -m pip install --upgrade pip
      shell: bash
    - name: Install Django
      run: python3.8 -m pip install Django
      shell: bash
    - name: Apply migrations
      run: python3.8 manage.py migrate
      shell: bash
      env:
        DJANGO_DB_HOST: ${{ inputs.DJANGO_DB_HOST }}
        DJANGO_DB_PORT: ${{ inputs.DJANGO_DB_PORT }}
        DJANGO_DB_NAME: ${{ inputs.DJANGO_DB_NAME }}
        DJANGO_DB_USER: ${{ inputs.DJANGO_DB_USER }}
        DJANGO_DB_PASSWORD: ${{ inputs.DJANGO_DB_PASSWORD }}
