name: 'Django Migrations Action'
description: 'Handles Django database migrations'
inputs:
  DB_HOST:
    description: 'Database host'
    required: true
  DB_PORT:
    description: 'Database port'
    required: true
  DB_NAME:
    description: 'Database name'
    required: true
  DB_USER:
    description: 'Database user'
    required: true
  DB_PASSWORD:
    description: 'Database password'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Django
      run: pip install Django
      shell: bash
      
    - name: Apply migrations
      run: |
        python manage.py migrate
      shell: bash
      env:
        DB_HOST: ${{ inputs.DB_HOST }}
        DB_PORT: ${{ inputs.DB_PORT }}
        DB_NAME: ${{ inputs.DB_NAME }}
        DB_USER: ${{ inputs.DB_USER }}
        DB_PASSWORD: ${{ inputs.DB_PASSWORD }}
